### ISSUE TITLE
支持配置请求模型

### ISSUE THREAD

**Issue by wangdj2020** [go-zoox/chatgpt-for-chatbot-feishu#12]
![model](https://user-images.githubusercontent.com/19581447/220243444-cd9ce6f0-bf07-4170-9225-f1e8a97304ac.jpg)

**Comment by whatwewant** [comment]
@wangdj2020 已支持自定义模型，如果需要更多参数，可以提供你的案例，便于考虑

**Comment by whatwewant** [comment]
可以通过环境变量 OPENAI_MODEL 自定义模型

**Comment by whatwewant** [comment]
如果是一键部署，可以通过一下方式升级：

```bash
$ export OPENAI_MODEL=<YOUR_MODEL>

$ zmicro service upgrade chatgpt-for-chatbot-feishu
```
