### ISSUE TITLE
苹果芯片拉取镜像错误

### ISSUE THREAD

**Issue by lanzhi-lee** [go-zoox/chatgpt-for-chatbot-feishu#19]
M1 Pro 报错如下：
```
➜  ~ docker pull whatwewant/chatgpt-for-chatbot-feishu:v1.3.2
v1.3.2: Pulling from whatwewant/chatgpt-for-chatbot-feishu
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by whatwewant** [comment]
这个问题是内置 cpolar （坑，不支持 arm64）引起的

如果要在 m1 测试，目前可以用二进制的方式安装：https://github.com/go-zoox/chatgpt-for-chatbot-feishu#%E4%BA%8C%E8%BF%9B%E5%88%B6

**Comment by whatwewant** [comment]
已修复，通过 `zmicro service upgrade chatgpt-for-chatbot-feishu` 一键升级
